words:
  - bugclerk
  - dpkg
  - gsub
  - imap
  - libbz
  - libc
  - libde
  - libfcgi
  - libheif
  - libkrb
  - libmagickcore
  - libsmbclient
  - nextcloud
  - ocrmypdf
  - pecl
  - pixbuf
  - procps
  - showmanual
  - smbclient
