name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - apps/**
  pull_request:
    paths:
      - apps/**

jobs:
  build:
    permissions:
      packages: write
      contents: read
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        containers:
          - app: tftpd-hpa
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Prepare
        id: prepare
        shell: bash
        run: |
          # Grab the version from the VERSION file
          VERSION=$(cat ./apps/${{ matrix.containers.app }}/VERSION )

          # Get the dockerhub token
          TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ixsystems/${{ matrix.containers.app }}:pull" | jq '.token' --raw-output)

          # Check if the "production" version already exists in dokerhub
          TAGS=$(curl -H "Authorization: Bearer $TOKEN" "https://index.docker.io/v2/ixsystems/${{ matrix.containers.app }}/tags/list")

          if echo "$TAGS" | grep -q "errors"; then
            echo "Failed to get tags from dockerhub"
            echo "$TAGS"
            exit 1
          fi

          EXISTS=$(echo "$TAGS" | jq --arg version "$VERSION" '.tags | index($version) != null')

          # If the version already exists, fail fast
          if [[ $EXISTS == "true" ]]; then
            echo "Version $VERSION already exists, please bump the version in the VERSION file."
            # If the "production" version already exists, fail fast
            exit 1
          fi

          # Initialize the output
          OUTPUT_VERSION="$VERSION"

          # If this is a pull request, append the PR number
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            OUTPUT_VERSION="$VERSION-pr${{ github.event.number }}"
          fi

          # Set the output
          echo "APP_VERSION=$OUTPUT_VERSION" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker images
        if: steps.prepare.outputs.APP_VERSION != ''
        uses: docker/build-push-action@91df6b874e498451163feb47610c87c4a218c1ee
        with:
          context: apps/${{ matrix.containers.app }}/
          push: true
          tags: |
            ixsystems/${{ matrix.containers.app }}:${{ steps.prepare.outputs.APP_VERSION }}
